services:
  lynx-fm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}
    container_name: lynx-fm
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - lynx-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lynx-fm.rule=Host(`lynx.fm`)"
      - "traefik.http.services.lynx-fm.loadbalancer.server.port=80"

networks:
  lynx-network:
    driver: bridge
