version: '3.8'

services:
  lynx-fm:
    build:
      context: .
      dockerfile: Dockerfile
    image: lynx-fm:latest
    container_name: lynx-fm
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - lynx-network

networks:
  lynx-network:
    driver: bridge
